/* cache-simulator.c */
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <assert.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>

/* Integer typedefs */
typedef int8_t   i8;
typedef int16_t  i16;
typedef int32_t  i32;
typedef int64_t  i64;
typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;

/**
 * Enum describing event that related to the cache state
 * @C_HIT: cache hit
 * @C_MISS: cache miss
 * @C_EVICT: cache eviction
 * @C_INV: replaced invalid line
 */
enum { C_HIT, C_MISS, C_EVICT, C_INV };

/**
 * cache_line_t: struct including info maintained per cache line
 * Layout: |tag|m|v|u|
 * Note: Unless the cache is fully associative and the block size is less
 *       than one word (or similar edge cases) 64 bits is enough to contain
 *       the tag, modifed bit, valid bit, and use bit
 * @tag: tag bits of cache line
 * @m: modified bit
 * @v: valid bit
 * @u: use bit
 */
typedef struct cache_line {
         u64 tag   : 61; // tag bits
         u8  m     : 1;  // modified bit
         u8  v     : 1;  // valid bit
         u8  u     : 1;  // use bit
} cache_line_t;

/**
 * cache_set_t: struct defining a set in the cache
 * @index: The index of the given set
 */
typedef struct cache_set {
        cache_line_t    *cache_lines; // cache lines in this set
        u16 index;      // index of set
} cache_set_t;

/**
 * cache_t: struct defining the complete cache
 * Notes: - A fully associative cache is interpreted as a cache containing
 *          1 set of |cache blocks| entries
 *        - A direct mapped cache is interpreted as a cache containing
 *          |cache blocks| sets of 1 entry
 *        - A set associative cache is intepreted as a cache containing
 *          |cache blocks|/associativity sets of associativity entries
 * @cache_sets: The sets contained in the cache
 * @nr_sets: The number of sets in the cache
 * @nr_set_entries: The number of entries per set in the cache (associativity)
 * @nr_offbits: The number of offset bits used to obtain the offset in a block
 *              i.e. log2(data block size)
 * @nr_ixbits: The number of index bits used to find the matching set for an
 *             address generated by a load or store
 */
typedef struct cache {
        cache_set_t     *cache_sets;    // sets in this cache
        u16             nr_sets;        // number of sets
        u8              nr_set_entries; // number of entries per set
        u8              nr_offbits;     // number of offset bits
        u8              nr_ixbits;      // number of index bits
} cache_t;

/**
 * log2i(): Computes log base 2 of an integer that is a power of 2; used to 
 *          calculate cache the number of offset and index bits based on the 
 *          cache parameters
 * @x: The value to compute the base 2 logarithm of
 * @return: The result of log2(x)
 */
u8 log2i(int x)
{
        u8 i = 0;
        for (; x > 1; x >>= 1, i++)
                ;
        return i;
}

/**
 * cache_create(): Creates a cache structure with parameters corresponding to
 *                 a given cache size, block size, and associativity
 * @cache_size: Total size of the cache in bytes
 * @data_block_size: Size of each data block/cache line in bytes
 * @associativity: Associativity of the cache (n == 1 -> direct mapped,
 *                 1 < n < number of cache lines -> n-way set associative,
 *                 n == number of cache lines -> fully associative)
 * @return: The allocated cache structure values initialized based on the
 *          given cache parameters
 */
cache_t *cache_create(u16 cache_size, u8 data_block_size, u8 associativity)
{
        /**
         * Calculated parameters:
         *  number of cache lines = cache size / data block size
         *  number of sets = number of cache lines / associativity
         *  number of entries per set = associativity
         *  number of bits in address for offset = log2(data block size)
         *  number of bits in address for index = log2(number of sets)
         */
        cache_t *cache = malloc(sizeof(*cache));
        u16 nr_cache_lines = cache_size / data_block_size;
        cache->nr_sets = nr_cache_lines / associativity;
        cache->nr_set_entries = associativity;
        cache->nr_offbits = log2i(data_block_size);
        cache->nr_ixbits = log2i(cache->nr_sets);
        
        /**
         * Allocate nr_sets sets of cache lines, initialize their set of cache
         * lines, and set the empty to be true
         */
        cache->cache_sets = malloc(sizeof(cache_set_t) * cache->nr_sets);

        int i;
        cache_set_t *set;
        for (i = 0, set = cache->cache_sets; i < cache->nr_sets; set++, i++) {
                set->index = i;
                set->cache_lines = calloc(cache->nr_sets, 
                                          sizeof(cache_line_t));
        }
        return cache;
}

/**
 * cache_destroy(): Deallocates the resources of the associated cache
 * @cache: The cache struct to free resources from
 */
void cache_destroy(cache_t *cache)
{
        for (cache_set_t *set = cache->cache_sets;
             set < cache->cache_sets + cache->nr_sets; set++)
                free(set->cache_lines);
        free(cache->cache_sets);
        free(cache);
}

/**
 * cache_index(): Extracts the index bits from an address
 * @cache: Cache providing parameters to determine which bits used for index
 * @addr: Address generated from a read or write
 * @return: Index bits of the generated address
 */
u64 cache_index(cache_t *cache, u64 addr)
{
        u64 mask = ((1 << cache->nr_ixbits) - 1) << cache->nr_offbits;
        return (addr & mask) >> cache->nr_offbits;
}

/**
 * cache_report(): Reports the occurence of a given event regarding the cache
 * @addr: Associated address to report on a hit, miss, or eviction
 * @rw: Indicates if a read or write generated the cache hit or cache miss
 * @event: Describes the event to report
 */
void cache_report(u64 addr, char rw, u8 event)
{
        switch (event) {
        case C_HIT:
                printf("Cache Hit: %s to %lx\n", 
                        (rw == 'r') ? "Read" : "Write", addr);
                break;
        case C_MISS:
                printf("Cache Miss: %s to %lx\n",
                        (rw == 'r') ? "Read" : "Write", addr);
                break;
        case C_EVICT:
                printf("Cache Eviction: Evicted %lx\n", addr);
                break;
        case C_INV:
                printf("Cache Replacement: Replaced invalid line\n");
                break;
        }
}

/**
 * cache_line_search(): Searches cache set in cache for a cache line with a,
 *                      matching tag; If the cache is fully associative, the
 *                      'set' is really the entire cache
 * @cache: Cache being searched
 * @set: Set in the cache that was indexed into and being searched
 * @addr: Address generated by read or write
 * @rw: If the address was generated by a read or write
 * @return: 1 if cache hit, 0 if cache miss
 */
int cache_line_search(cache_t *cache, cache_set_t *set, u64 addr, char rw)
{       
        /* Extract tag from the given address */
        u64 tag = addr >> (cache->nr_ixbits + cache->nr_offbits);
        
        /* If direct mapped, only one comparison */
        if (cache->nr_set_entries == 1) {
                cache_line_t *line = set->cache_lines;
                if (line->v && line->tag == tag) {
                        cache_report(addr, rw, C_HIT);
                        return 1;
                }
                cache_report(addr, rw, C_MISS);
                return 0;
        }
        
        /* If set associative or fully associative, search entire set space */
        cache_line_t *line, *end = set->cache_lines + cache->nr_set_entries;
        for (line = set->cache_lines; line < end; line++) {
                if (line->v && line->tag == tag) {
                        cache_report(addr, rw, C_HIT);
                        return 1;
                }
        }
        cache_report(addr, rw, C_MISS);
        return 0;
}

/**
 * cache_replace_line(): Replace a line in the specified set with LRU
 *                       approximation
 * @cache: Cache which given set resides in
 * @set: Set to evict a line from
 * @addr: Address to replace with evicted line
 * @rw: Whether the cache miss originated from a read or a write
 * @return: 1 if a line was successfully replaced, 0 otherwise
 */
int cache_replace_line(cache_t *cache, cache_set_t *set, u64 addr, char rw)
{
        u64 tag = addr >> (cache->nr_ixbits + cache->nr_offbits);
        for (int i = 0;; i = (i + 1) % cache->nr_set_entries) {
                cache_line_t *line = set->cache_lines + i;
                if (line->v && line->u) {
                        /* Unset use bit if line is valid and used */
                        line->u = 0;
                        continue;
                } else if (!(line->v)) {
                        /* If line is invalid, it is free to replace */
                        line->tag = tag;
                        line->v = 1;
                        if (rw == 'w')
                                line->m = 1;
                        cache_report(0, 0, C_INV);
                        return 1;
                } else if (!(line->u)) {
                        /* If the use bit is not set, evict this line */
                        u64 evict_tag = line->tag << cache->nr_offbits;
                        line->tag = tag;
                        line->v = 1;
                        line->u = 1;
                        if (rw == 'w')
                                line->m = 1;
                        cache_report(evict_tag, 0, C_EVICT);
                        return 1;
                }
        }
}

/*
 * cache_simulate(): Simulates cache with reads and writes reported from
 *                   binary instrumented with llvm module pass
 * @cache: Cache to use for simulation
 * @return: 1 if simulation is successful, 0 if error occurs
 */
int cache_simulate(cache_t *cache, char mode)
{       
        /* Disable stdout during simulation if in summary mode */
        int fd;
        if (mode == 's') {
                fd = open("/dev/stdout", O_WRONLY);
                if (fd < 0) {
                        perror("open");
                        return -1;
                }
                close(STDOUT_FILENO);
        }

        int nr_hits = 0, nr_misses = 0; // number of cache hits and misses
        u64  addr;                      // address of read or write
        char rw;                        // if access was a read or write
        
        while (!feof(stdin)) {
                if (scanf("%c%lx\n", &rw, &addr) < 2) {
                        fprintf(stderr, "Failed to retrieve load/store info\n");
                        return -1;
                }
                /* Index into set corresponding to the address index bits */
                cache_set_t *set = cache->cache_sets + cache_index(cache, addr);

                if (cache_line_search(cache, set, addr, rw))
                        nr_hits++;
                else {
                        nr_misses++;
                        assert(cache_replace_line(cache, set, addr, rw) == 1);
                }
        }
        
        /* Display of summary */
        if (mode == 's') {
                char buf[512];
                snprintf(buf, sizeof(buf),
                         "Number of total memory accesses:\t%d\n"
                         "Number of cache hits:\t\t\t%d\n"
                         "Number of cache misses:\t\t\t%d\n"
                         "Percent of cache hits:\t\t\t%f\n",
                         nr_hits + nr_misses, nr_hits, nr_misses,
                         (float)nr_hits / (float)(nr_hits + nr_misses));
                write(fd, buf, strlen(buf));
        }
        return 0;
}

int main(int argc, char *argv[])
{
        if (argc < 7) {
                fprintf(stderr, "Usage: ./cache-simulator "
                                "--data-block-size [N] "
                                "--cache-size [N] "
                                "--mode [verbose | summary] "
                                "--associativity [N] (optional)\n");
                exit(1);
        }
        
        u8 data_block_size = 0;
        u16 cache_size = 0;
        u8 associativity = 0;
        char mode = 0;
        
        for (int i = 1; i < argc; i += 2) {
                if (!strcmp("--data-block-size", argv[i]))
                        data_block_size = atoi(argv[i + 1]);
                else if (!strcmp("--cache-size", argv[i]))
                        cache_size = atoi(argv[i + 1]);
                else if (!strcmp("--mode", argv[i]))
                        mode = (strcmp(argv[i + 1], "verbose")) ? 's' : 'v';
                else if (!strcmp("--associativity", argv[i]))
                        associativity = atoi(argv[i + 1]);
        }
        
        if (!(data_block_size && cache_size && mode)) {
                fprintf(stderr, "A data block size, cache size or mode "
                                "were not selected\n");
                exit(1);
        } else if (associativity == 0) {
                /* Default to fully associative cache */
                associativity = cache_size / data_block_size;
        }

        cache_t *cache = cache_create(cache_size, data_block_size, 
                                      associativity);
        if (cache_simulate(cache, mode) < 0) {
                fprintf(stderr, "cache-simulation failed. Exiting...\n");
                cache_destroy(cache);
                exit(1);
        }

        cache_destroy(cache);
        exit(0);
}
